[providers]
nodejs = "22"

[phases.setup]
nixPkgs = ["nodejs-22_x", "npm-9_x"]

[phases.install]
cmd = "npm ci"

[phases.build]
cmd = "npx turbo run build --filter=web"

[start]
cmd = "cd apps/web && npm start"