[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[[services]]
name = "web"

[services.web.build]
buildCommand = "npm install && npm run build --workspace=apps/web"

[services.web.deploy]
startCommand = "npm start --workspace=apps/web"

[[services]]
name = "worker"  
source = "packages/queue"

[services.worker.deploy]
startCommand = "node worker.js"

[environments]
production.PORT = 3000
production.NODE_ENV = "production"